version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    environment:
      - APP_NAME=FlaskTest
    expose:
      - 5000

  flask2:
    build: ./flask
    container_name: flask2
    expose:
    - 5000    

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  mysql:
    build: ./mysql
    container_name: mysql
    restart: always
    expose:
      - 3306
